AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: ica-backend
    Description: mission management system that provides a range of microservices to ICA operators, such as mission planning, target tracking, communication, and reporting.
    Author: giang
    SpdxLicenseId: GPL-3.0-only
    LicenseUrl: ../LICENSE
    ReadmeUrl: ../README.md
    Labels: ['serverless', 'microservices', 'aws', 'dotnet']
    HomePageUrl: https://github.com/ICA-taskmaster/ICA-Taskmaster
    SemanticVersion: 0.0.2
    SourceCodeUrl: https://github.com/ICA-taskmaster/ICA-Taskmaster

Resources:
  AgentServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../AgentService/
      Handler: AgentService::AgentService.Function::FunctionHandler
      Runtime: dotnet6.0
      Events:
        GetAllAgentsApi:
          Type: Api
          Properties:
            Path: /api/Agents
            Method: post
        GetAgentByIdApi:
          Type: Api
          Properties:
            Path: /api/Agents/{id}
            Method: get

  EquipmentServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../EquipmentService/
      Handler: EquipmentService::EquipmentService.Function::FunctionHandler
      Runtime: dotnet6.0
      Events:
        GetEquipmentsByAgentIdApi:
          Type: Api
          Properties:
            Path: /api/c/agents/{agentId}/equipments
            Method: get
        GetEquipmentByIdApi:
          Type: Api
          Properties:
            Path: /api/c/agents/{agentId}/equipments/{equipmentId}
            Method: get
        CreateEquipmentApi:
          Type: Api
          Properties:
            Path: /api/c/agents/{agentId}/equipments
            Method: post

  MissionServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../MissionService/
      Handler: MissionService::MissionService.Function::FunctionHandler
      Runtime: dotnet6.0
      Events:
        GetMissionsByAgentIdApi:
          Type: Api
          Properties:
            Path: /api/c/agents/{agentId}/missions
            Method: get
        GetMissionByIdApi:
          Type: Api
          Properties:
            Path: /api/c/agents/{agentId}/missions/{missionId}
            Method: get

Outputs:
  ApiEndpoint:
    Description: API endpoint URL for the microservices
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
