apiVersion: apps/v1
kind: Deployment
metadata:
  name: agents-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agentservice
  template:
    metadata:
      labels:
        environment: production
        app: agentservice
    spec:
      containers:
        - name: agentservice
          image: extiriority/agentservice:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: agents-api-srv
spec:
  selector:
    app: agentservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80