apiVersion: apps/v1
kind: Deployment
metadata:
  name: equipments-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: equipmentservice
  template:
    metadata:
      labels:
        environment: production
        app: equipmentservice
    spec:
      containers:
        - name: equipmentservice
          image: extiriority/equipmentservice:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: equipments-api-srv
spec:
  selector:
    app: equipmentservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80