name: JMeter Performance Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build:
    name: Testing performance
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: PerfAction for JMeter
      # You may pin to the exact commit or the version.
      # uses: QAInsights/PerfAction@f3959d0a69e7f23949add25d7e34a3ae167d6443
      uses: QAInsights/PerfAction@v3.1
      with:
        # jmeter test plan to execute
        test-plan-path: './Performance-Test.jmx'
    - name: Upload Results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: result.jtl
