name: JMeter Performance Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build:
    name: Testing performance
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          
      - name: Start RabbitMQ
        run: |
          docker run -d --name rabbitmq -p 5672:5672 rabbitmq:latest
      - name: Restore & build Agent Service
        run: |
          cd ./AgentService
          dotnet restore
          dotnet build --no-restore
      - name: Restore & build Equipment Service
        run: |
          cd ./EquipmentService
          dotnet restore
          dotnet build --no-restore
      - name: Start Services
        run: |
          cd ./AgentService
          dotnet run --no-build &
          sleep 30s
          cd ../EquipmentService
          dotnet run --no-build  &
          sleep 30s